[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "cd telegram-bots-catalog && npm run preview -- --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
